version: '3'
services:
    app: 
        container_name: backend_mongo
        restart: always
        build: .
        ports:
            - "5000:4000"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
    mongo: 
        container_name: mongo_database
        image: mongo
        ports:
            - "27000:27017"
        logging:
            driver: none