export interface Objdyn {
    code?: string,
    adm?: string,
    company?: string,
    plant_type?: string,
    plant_code?: string,
    plant_name?: string,
    a?: string,
    b?: string,
    c?: string,
    d?: string,
    e?: string,
    f?: string,
    g?: string,
    h?: string,
    i?: string,
    j?: string,
    k?: string,
    l?: string,
    m?: string,
    n?: string,
    o?: string,
    p?: string,
    q?: string,
}
